# Generated by Django 3.2.5 on 2022-07-19 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='正文')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期')),
                ('comment_num', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('like_num', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('visit_num', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='类别id')),
                ('cat_name', models.CharField(max_length=20, verbose_name='类别名称')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Friendlink',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False, verbose_name='友链ID')),
                ('link_url', models.URLField(verbose_name='友链地址')),
                ('link_desc', models.CharField(max_length=100, verbose_name='友链描述')),
                ('link_name', models.CharField(max_length=20, verbose_name='友链名称')),
                ('link_avatar', models.ImageField(default='media/default.jpg', upload_to='media/uploads/', verbose_name='友链头像')),
            ],
            options={
                'db_table': 'friendlinks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('created_time', models.CharField(default=django.utils.timezone.now, max_length=50)),
                ('comment_num', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('avatar', models.ImageField(default='media/default.jpg', upload_to='media')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'blog_user',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('author', models.CharField(max_length=20, verbose_name='评论作者')),
                ('author_email', models.EmailField(max_length=254, verbose_name='作者邮箱')),
                ('author_link', models.URLField(default='', null=True, verbose_name='作者链接')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论日期')),
                ('content', mdeditor.fields.MDTextField(null=True, verbose_name='评论正文')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-comment_date'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
