# Generated by Django 3.2.5 on 2022-07-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('article_cat', models.CharField(max_length=20, verbose_name='文章分类')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('publish_date', models.DateTimeField(default='2022-07-11', verbose_name='发布日期')),
                ('comment_num', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('like_num', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('visit_num', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/default.jpg', upload_to='media'),
        ),
    ]
