# Generated by Django 3.2.5 on 2022-07-11 16:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220711_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendlink',
            fields=[
                ('link_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='友链ID')),
                ('link_url', models.URLField(verbose_name='友链地址')),
                ('link_desc', models.CharField(max_length=100, verbose_name='友链描述')),
                ('link_name', models.CharField(max_length=20, verbose_name='友链名称')),
                ('link_avatar', models.ImageField(default='media/default.jpg', upload_to='media', verbose_name='友链头像')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default='2022-07-12', verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.CharField(default='2022-07-12', max_length=50),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('comment_author', models.CharField(max_length=20, verbose_name='评论作者')),
                ('comment_author_email', models.EmailField(max_length=254, verbose_name='作者邮箱')),
                ('comment_author_link', models.URLField(default='', verbose_name='作者链接')),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2022, 7, 12, 0, 45, 37, 524179), verbose_name='评论日期')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='类别ID')),
                ('cat_name', models.CharField(max_length=20, verbose_name='类别名称')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
    ]
