# Generated by Django 3.2.5 on 2022-07-21 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220720_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_link',
            field=models.URLField(blank=True, default='', null=True, verbose_name='作者链接'),
        ),
        migrations.CreateModel(
            name='Subcomment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='子评论ID')),
                ('author', models.CharField(max_length=20, verbose_name='子评论作者')),
                ('author_email', models.EmailField(max_length=254, verbose_name='作者邮箱')),
                ('author_link', models.URLField(blank=True, default='', null=True, verbose_name='作者链接')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论日期')),
                ('content', mdeditor.fields.MDTextField(null=True, verbose_name='子评论正文')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
            ],
            options={
                'verbose_name': '子评论',
                'verbose_name_plural': '所有子评论',
                'db_table': 'subcomments',
                'ordering': ['-comment_date'],
            },
        ),
    ]
