# Generated by Django 3.2.5 on 2022-07-12 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author_email',
            new_name='author_email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author_link',
            new_name='author_link',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='评论正文'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 23, 7, 23, 43742), verbose_name='评论日期'),
        ),
    ]
