# Generated by Django 3.2.5 on 2022-07-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220721_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('per', '已通过'), ('npr', '未通过')], default='npr', max_length=5, verbose_name='评论状态'),
        ),
    ]
