# Generated by Django 3.2.5 on 2022-07-21 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment_num',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='like_num',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='visit_num',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='浏览数'),
        ),
    ]
