# Generated by Django 3.2.20 on 2023-08-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220721_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlink',
            name='link_avatar',
            field=models.ImageField(default='default.jpg', upload_to='uploads/', verbose_name='友链头像'),
        ),
    ]
