# Generated by Django 3.2.5 on 2022-07-13 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220712_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 17, 5, 3, 599565), verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 17, 5, 3, 600541), verbose_name='评论日期'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.CharField(default='2022-07-13', max_length=50),
        ),
    ]
