# Generated by Django 3.2.5 on 2022-07-13 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220713_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 17, 6, 44, 494222), verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 17, 6, 44, 495198), verbose_name='评论日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.CharField(default=datetime.datetime(2022, 7, 13, 17, 6, 44, 494222), max_length=50),
        ),
    ]
