# Generated by Django 3.2.5 on 2022-07-16 17:21

from django.db import migrations, models
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220713_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
