# Generated by Django 3.2.5 on 2022-07-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220717_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='类别ID'),
        ),
        migrations.AlterField(
            model_name='friendlink',
            name='link_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='友链ID'),
        ),
    ]
