# Generated by Django 3.2.5 on 2022-07-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220717_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='类别id'),
        ),
    ]
