# Generated by Django 3.2.5 on 2022-07-17 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_category_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_link',
            field=models.URLField(default='', null=True, verbose_name='作者链接'),
        ),
        migrations.AlterField(
            model_name='friendlink',
            name='link_avatar',
            field=models.ImageField(default='media/default.jpg', upload_to='uploads', verbose_name='友链头像'),
        ),
    ]
